  import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.scss";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import 'animate.css'

const raleway = Raleway({
  weight: ["400", "500", "900", "700", "800"],
  subsets: ["latin"],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Rivero Trust Bank Plc",
  description: "Generated by Paks",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}


